# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5855a53d5b82f7cf0b490ab8fcc8f219f65a2f88818254a77d6cb3bb76f44b847cab46afc1406e8b43d94bb665cd7f778889f931bb9282f87d6310f1c705e6d4

test:
  secret_key_base: a8eac31402e55065276b12242132af90ec99db62ca4175920c8f3318c228434b3461ca8b950d852008949a77da93b93637dfdbaf6b6099ff305239d11ca789f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
